'use client'
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports

import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  Button,
  ColorSchemeScript,
  createTheme,
  MantineProvider,
  MantineThemeProvider,
} from "@mantine/core";

// export const metadata: Metadata = {
//   title: "My Mantine app",
//   description: "I have followed setup instructions carefully",
// };
const inter = Inter({ subsets: ["latin"] });
const theme = createTheme({
  components: {
    Button: Button.extend({
      defaultProps: {
        color: "orange",
        // variant: "outline",
      },
    }),
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineThemeProvider theme={theme}>
          <MantineProvider>{children}</MantineProvider>
        </MantineThemeProvider>
      </body>
    </html>
  );
}
